name: SimplifiedByAnnie
favicon: null
layout_spectrum: 0.8025987106375396
typography_spectrum: 0.05688999709673226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8531474801711738
  lightness: 0.024471446871757507
  saturation: 0.24561112257651985
  rhythmicContrast: 0.27333865663968027
purpose: []
