name: SimplifiedByAnnie
favicon: null
layout_spectrum: 0.49556
typography_spectrum: 0.28687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28394b'
    - '#090000'
    - '#bcbb88'
    - '#5381a3'
    - '#fef677'
  brandStrength: 0
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
